
@port = 127.0.0.1:9901/


###创建博客
POST http://{{port}}blogs/write
content-type: application/json

{
    "title": "test1",
    "content": "#123\n```\n console.log(123) \n```",
    "author": "Doraemon",
    "navid": "622efba8e61f6f9bb859927f"
}

###获取博客文章
GET http://{{port}}blogs/blog_paper?id=622efba8e61f6f9bb859927f

###创建nav
POST http://{{port}}blogs/blogNav
content-type: application/json

{
    "state":"1",
    "title":"Node JS"
}

### 获取nav
GET http://{{port}}blogs/blogNav

### 获取nTitle
GET http://{{port}}blogs/getTitle?navid=6232e3422ec954196d961584