
###用户登录
GET http://127.0.0.1:9901/user/login HTTP/1.1

###用户注册
POST http://127.0.0.1:9901/user/regist HTTP/1.1
content-type: application/json

{
    "uid":"admin1",
    "pwd":"123456"
}

###获取路由和列表
get http://127.0.0.1:9901/list/route HTTP/1.1


